// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DELFOS_DELFOS_FB_H_
#define FLATBUFFERS_GENERATED_DELFOS_DELFOS_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace delfos {
namespace fb {

struct Node;
struct NodeBuilder;
struct NodeT;

struct Edge;
struct EdgeBuilder;
struct EdgeT;

struct ManifestEntry;
struct ManifestEntryBuilder;
struct ManifestEntryT;

struct Snapshot;
struct SnapshotBuilder;
struct SnapshotT;

enum NodeType : int8_t {
  NodeType_Cue = 0,
  NodeType_Tag = 1,
  NodeType_Content = 2,
  NodeType_MIN = NodeType_Cue,
  NodeType_MAX = NodeType_Content
};

inline const NodeType (&EnumValuesNodeType())[3] {
  static const NodeType values[] = {
    NodeType_Cue,
    NodeType_Tag,
    NodeType_Content
  };
  return values;
}

inline const char * const *EnumNamesNodeType() {
  static const char * const names[4] = {
    "Cue",
    "Tag",
    "Content",
    nullptr
  };
  return names;
}

inline const char *EnumNameNodeType(NodeType e) {
  if (::flatbuffers::IsOutRange(e, NodeType_Cue, NodeType_Content)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNodeType()[index];
}

enum EdgeType : int8_t {
  EdgeType_CueOf = 0,
  EdgeType_TaggedWith = 1,
  EdgeType_PartOfTopic = 2,
  EdgeType_RedirectsTo = 3,
  EdgeType_MIN = EdgeType_CueOf,
  EdgeType_MAX = EdgeType_RedirectsTo
};

inline const EdgeType (&EnumValuesEdgeType())[4] {
  static const EdgeType values[] = {
    EdgeType_CueOf,
    EdgeType_TaggedWith,
    EdgeType_PartOfTopic,
    EdgeType_RedirectsTo
  };
  return values;
}

inline const char * const *EnumNamesEdgeType() {
  static const char * const names[5] = {
    "CueOf",
    "TaggedWith",
    "PartOfTopic",
    "RedirectsTo",
    nullptr
  };
  return names;
}

inline const char *EnumNameEdgeType(EdgeType e) {
  if (::flatbuffers::IsOutRange(e, EdgeType_CueOf, EdgeType_RedirectsTo)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEdgeType()[index];
}

enum NodeStatus : int8_t {
  NodeStatus_Active = 0,
  NodeStatus_Deleted = 1,
  NodeStatus_MIN = NodeStatus_Active,
  NodeStatus_MAX = NodeStatus_Deleted
};

inline const NodeStatus (&EnumValuesNodeStatus())[2] {
  static const NodeStatus values[] = {
    NodeStatus_Active,
    NodeStatus_Deleted
  };
  return values;
}

inline const char * const *EnumNamesNodeStatus() {
  static const char * const names[3] = {
    "Active",
    "Deleted",
    nullptr
  };
  return names;
}

inline const char *EnumNameNodeStatus(NodeStatus e) {
  if (::flatbuffers::IsOutRange(e, NodeStatus_Active, NodeStatus_Deleted)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNodeStatus()[index];
}

enum CueType : int8_t {
  CueType_Symbol = 0,
  CueType_Concept = 1,
  CueType_ErrorMessage = 2,
  CueType_MIN = CueType_Symbol,
  CueType_MAX = CueType_ErrorMessage
};

inline const CueType (&EnumValuesCueType())[3] {
  static const CueType values[] = {
    CueType_Symbol,
    CueType_Concept,
    CueType_ErrorMessage
  };
  return values;
}

inline const char * const *EnumNamesCueType() {
  static const char * const names[4] = {
    "Symbol",
    "Concept",
    "ErrorMessage",
    nullptr
  };
  return names;
}

inline const char *EnumNameCueType(CueType e) {
  if (::flatbuffers::IsOutRange(e, CueType_Symbol, CueType_ErrorMessage)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCueType()[index];
}

enum TagCategory : int8_t {
  TagCategory_ModulePath = 0,
  TagCategory_ArchLayer = 1,
  TagCategory_PatternType = 2,
  TagCategory_LangConstruct = 3,
  TagCategory_Language = 4,
  TagCategory_MIN = TagCategory_ModulePath,
  TagCategory_MAX = TagCategory_Language
};

inline const TagCategory (&EnumValuesTagCategory())[5] {
  static const TagCategory values[] = {
    TagCategory_ModulePath,
    TagCategory_ArchLayer,
    TagCategory_PatternType,
    TagCategory_LangConstruct,
    TagCategory_Language
  };
  return values;
}

inline const char * const *EnumNamesTagCategory() {
  static const char * const names[6] = {
    "ModulePath",
    "ArchLayer",
    "PatternType",
    "LangConstruct",
    "Language",
    nullptr
  };
  return names;
}

inline const char *EnumNameTagCategory(TagCategory e) {
  if (::flatbuffers::IsOutRange(e, TagCategory_ModulePath, TagCategory_Language)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTagCategory()[index];
}

enum ContentKind : int8_t {
  ContentKind_Function = 0,
  ContentKind_Class = 1,
  ContentKind_Module = 2,
  ContentKind_Commit = 3,
  ContentKind_Test = 4,
  ContentKind_MIN = ContentKind_Function,
  ContentKind_MAX = ContentKind_Test
};

inline const ContentKind (&EnumValuesContentKind())[5] {
  static const ContentKind values[] = {
    ContentKind_Function,
    ContentKind_Class,
    ContentKind_Module,
    ContentKind_Commit,
    ContentKind_Test
  };
  return values;
}

inline const char * const *EnumNamesContentKind() {
  static const char * const names[6] = {
    "Function",
    "Class",
    "Module",
    "Commit",
    "Test",
    nullptr
  };
  return names;
}

inline const char *EnumNameContentKind(ContentKind e) {
  if (::flatbuffers::IsOutRange(e, ContentKind_Function, ContentKind_Test)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesContentKind()[index];
}

enum MemoryLayer : int8_t {
  MemoryLayer_Episodic = 0,
  MemoryLayer_Semantic = 1,
  MemoryLayer_Topic = 2,
  MemoryLayer_MIN = MemoryLayer_Episodic,
  MemoryLayer_MAX = MemoryLayer_Topic
};

inline const MemoryLayer (&EnumValuesMemoryLayer())[3] {
  static const MemoryLayer values[] = {
    MemoryLayer_Episodic,
    MemoryLayer_Semantic,
    MemoryLayer_Topic
  };
  return values;
}

inline const char * const *EnumNamesMemoryLayer() {
  static const char * const names[4] = {
    "Episodic",
    "Semantic",
    "Topic",
    nullptr
  };
  return names;
}

inline const char *EnumNameMemoryLayer(MemoryLayer e) {
  if (::flatbuffers::IsOutRange(e, MemoryLayer_Episodic, MemoryLayer_Topic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMemoryLayer()[index];
}

struct NodeT : public ::flatbuffers::NativeTable {
  typedef Node TableType;
  std::string id{};
  delfos::fb::NodeType type = delfos::fb::NodeType_Cue;
  delfos::fb::NodeStatus status = delfos::fb::NodeStatus_Active;
  int64_t indexed_at = 0;
  int64_t deleted_at = 0;
  std::string deleted_by_commit{};
  std::string source_file{};
  std::string git_sha{};
  delfos::fb::CueType cue_type = delfos::fb::CueType_Symbol;
  std::string text{};
  delfos::fb::TagCategory category = delfos::fb::TagCategory_ModulePath;
  std::string value{};
  delfos::fb::ContentKind kind = delfos::fb::ContentKind_Function;
  delfos::fb::MemoryLayer memory_layer = delfos::fb::MemoryLayer_Episodic;
  std::string symbol_name{};
  std::string signature{};
  std::string docstring{};
  std::string body{};
  std::vector<float> embedding{};
  std::string embedding_model{};
  std::string embedding_model_version{};
};

struct Node FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeT NativeTableType;
  typedef NodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_STATUS = 8,
    VT_INDEXED_AT = 10,
    VT_DELETED_AT = 12,
    VT_DELETED_BY_COMMIT = 14,
    VT_SOURCE_FILE = 16,
    VT_GIT_SHA = 18,
    VT_CUE_TYPE = 20,
    VT_TEXT = 22,
    VT_CATEGORY = 24,
    VT_VALUE = 26,
    VT_KIND = 28,
    VT_MEMORY_LAYER = 30,
    VT_SYMBOL_NAME = 32,
    VT_SIGNATURE = 34,
    VT_DOCSTRING = 36,
    VT_BODY = 38,
    VT_EMBEDDING = 40,
    VT_EMBEDDING_MODEL = 42,
    VT_EMBEDDING_MODEL_VERSION = 44
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  delfos::fb::NodeType type() const {
    return static_cast<delfos::fb::NodeType>(GetField<int8_t>(VT_TYPE, 0));
  }
  delfos::fb::NodeStatus status() const {
    return static_cast<delfos::fb::NodeStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  int64_t indexed_at() const {
    return GetField<int64_t>(VT_INDEXED_AT, 0);
  }
  int64_t deleted_at() const {
    return GetField<int64_t>(VT_DELETED_AT, 0);
  }
  const ::flatbuffers::String *deleted_by_commit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DELETED_BY_COMMIT);
  }
  const ::flatbuffers::String *source_file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_FILE);
  }
  const ::flatbuffers::String *git_sha() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GIT_SHA);
  }
  delfos::fb::CueType cue_type() const {
    return static_cast<delfos::fb::CueType>(GetField<int8_t>(VT_CUE_TYPE, 0));
  }
  const ::flatbuffers::String *text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
  }
  delfos::fb::TagCategory category() const {
    return static_cast<delfos::fb::TagCategory>(GetField<int8_t>(VT_CATEGORY, 0));
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  delfos::fb::ContentKind kind() const {
    return static_cast<delfos::fb::ContentKind>(GetField<int8_t>(VT_KIND, 0));
  }
  delfos::fb::MemoryLayer memory_layer() const {
    return static_cast<delfos::fb::MemoryLayer>(GetField<int8_t>(VT_MEMORY_LAYER, 0));
  }
  const ::flatbuffers::String *symbol_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SYMBOL_NAME);
  }
  const ::flatbuffers::String *signature() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SIGNATURE);
  }
  const ::flatbuffers::String *docstring() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DOCSTRING);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  const ::flatbuffers::Vector<float> *embedding() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_EMBEDDING);
  }
  const ::flatbuffers::String *embedding_model() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMBEDDING_MODEL);
  }
  const ::flatbuffers::String *embedding_model_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMBEDDING_MODEL_VERSION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyField<int64_t>(verifier, VT_INDEXED_AT, 8) &&
           VerifyField<int64_t>(verifier, VT_DELETED_AT, 8) &&
           VerifyOffset(verifier, VT_DELETED_BY_COMMIT) &&
           verifier.VerifyString(deleted_by_commit()) &&
           VerifyOffset(verifier, VT_SOURCE_FILE) &&
           verifier.VerifyString(source_file()) &&
           VerifyOffset(verifier, VT_GIT_SHA) &&
           verifier.VerifyString(git_sha()) &&
           VerifyField<int8_t>(verifier, VT_CUE_TYPE, 1) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           VerifyField<int8_t>(verifier, VT_CATEGORY, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyField<int8_t>(verifier, VT_MEMORY_LAYER, 1) &&
           VerifyOffset(verifier, VT_SYMBOL_NAME) &&
           verifier.VerifyString(symbol_name()) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyString(signature()) &&
           VerifyOffset(verifier, VT_DOCSTRING) &&
           verifier.VerifyString(docstring()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyOffset(verifier, VT_EMBEDDING) &&
           verifier.VerifyVector(embedding()) &&
           VerifyOffset(verifier, VT_EMBEDDING_MODEL) &&
           verifier.VerifyString(embedding_model()) &&
           VerifyOffset(verifier, VT_EMBEDDING_MODEL_VERSION) &&
           verifier.VerifyString(embedding_model_version()) &&
           verifier.EndTable();
  }
  NodeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NodeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Node> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NodeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NodeBuilder {
  typedef Node Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Node::VT_ID, id);
  }
  void add_type(delfos::fb::NodeType type) {
    fbb_.AddElement<int8_t>(Node::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_status(delfos::fb::NodeStatus status) {
    fbb_.AddElement<int8_t>(Node::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_indexed_at(int64_t indexed_at) {
    fbb_.AddElement<int64_t>(Node::VT_INDEXED_AT, indexed_at, 0);
  }
  void add_deleted_at(int64_t deleted_at) {
    fbb_.AddElement<int64_t>(Node::VT_DELETED_AT, deleted_at, 0);
  }
  void add_deleted_by_commit(::flatbuffers::Offset<::flatbuffers::String> deleted_by_commit) {
    fbb_.AddOffset(Node::VT_DELETED_BY_COMMIT, deleted_by_commit);
  }
  void add_source_file(::flatbuffers::Offset<::flatbuffers::String> source_file) {
    fbb_.AddOffset(Node::VT_SOURCE_FILE, source_file);
  }
  void add_git_sha(::flatbuffers::Offset<::flatbuffers::String> git_sha) {
    fbb_.AddOffset(Node::VT_GIT_SHA, git_sha);
  }
  void add_cue_type(delfos::fb::CueType cue_type) {
    fbb_.AddElement<int8_t>(Node::VT_CUE_TYPE, static_cast<int8_t>(cue_type), 0);
  }
  void add_text(::flatbuffers::Offset<::flatbuffers::String> text) {
    fbb_.AddOffset(Node::VT_TEXT, text);
  }
  void add_category(delfos::fb::TagCategory category) {
    fbb_.AddElement<int8_t>(Node::VT_CATEGORY, static_cast<int8_t>(category), 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(Node::VT_VALUE, value);
  }
  void add_kind(delfos::fb::ContentKind kind) {
    fbb_.AddElement<int8_t>(Node::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_memory_layer(delfos::fb::MemoryLayer memory_layer) {
    fbb_.AddElement<int8_t>(Node::VT_MEMORY_LAYER, static_cast<int8_t>(memory_layer), 0);
  }
  void add_symbol_name(::flatbuffers::Offset<::flatbuffers::String> symbol_name) {
    fbb_.AddOffset(Node::VT_SYMBOL_NAME, symbol_name);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::String> signature) {
    fbb_.AddOffset(Node::VT_SIGNATURE, signature);
  }
  void add_docstring(::flatbuffers::Offset<::flatbuffers::String> docstring) {
    fbb_.AddOffset(Node::VT_DOCSTRING, docstring);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(Node::VT_BODY, body);
  }
  void add_embedding(::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding) {
    fbb_.AddOffset(Node::VT_EMBEDDING, embedding);
  }
  void add_embedding_model(::flatbuffers::Offset<::flatbuffers::String> embedding_model) {
    fbb_.AddOffset(Node::VT_EMBEDDING_MODEL, embedding_model);
  }
  void add_embedding_model_version(::flatbuffers::Offset<::flatbuffers::String> embedding_model_version) {
    fbb_.AddOffset(Node::VT_EMBEDDING_MODEL_VERSION, embedding_model_version);
  }
  explicit NodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Node> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Node>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Node> CreateNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    delfos::fb::NodeType type = delfos::fb::NodeType_Cue,
    delfos::fb::NodeStatus status = delfos::fb::NodeStatus_Active,
    int64_t indexed_at = 0,
    int64_t deleted_at = 0,
    ::flatbuffers::Offset<::flatbuffers::String> deleted_by_commit = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_file = 0,
    ::flatbuffers::Offset<::flatbuffers::String> git_sha = 0,
    delfos::fb::CueType cue_type = delfos::fb::CueType_Symbol,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0,
    delfos::fb::TagCategory category = delfos::fb::TagCategory_ModulePath,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0,
    delfos::fb::ContentKind kind = delfos::fb::ContentKind_Function,
    delfos::fb::MemoryLayer memory_layer = delfos::fb::MemoryLayer_Episodic,
    ::flatbuffers::Offset<::flatbuffers::String> symbol_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> signature = 0,
    ::flatbuffers::Offset<::flatbuffers::String> docstring = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> embedding = 0,
    ::flatbuffers::Offset<::flatbuffers::String> embedding_model = 0,
    ::flatbuffers::Offset<::flatbuffers::String> embedding_model_version = 0) {
  NodeBuilder builder_(_fbb);
  builder_.add_deleted_at(deleted_at);
  builder_.add_indexed_at(indexed_at);
  builder_.add_embedding_model_version(embedding_model_version);
  builder_.add_embedding_model(embedding_model);
  builder_.add_embedding(embedding);
  builder_.add_body(body);
  builder_.add_docstring(docstring);
  builder_.add_signature(signature);
  builder_.add_symbol_name(symbol_name);
  builder_.add_value(value);
  builder_.add_text(text);
  builder_.add_git_sha(git_sha);
  builder_.add_source_file(source_file);
  builder_.add_deleted_by_commit(deleted_by_commit);
  builder_.add_id(id);
  builder_.add_memory_layer(memory_layer);
  builder_.add_kind(kind);
  builder_.add_category(category);
  builder_.add_cue_type(cue_type);
  builder_.add_status(status);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Node> CreateNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    delfos::fb::NodeType type = delfos::fb::NodeType_Cue,
    delfos::fb::NodeStatus status = delfos::fb::NodeStatus_Active,
    int64_t indexed_at = 0,
    int64_t deleted_at = 0,
    const char *deleted_by_commit = nullptr,
    const char *source_file = nullptr,
    const char *git_sha = nullptr,
    delfos::fb::CueType cue_type = delfos::fb::CueType_Symbol,
    const char *text = nullptr,
    delfos::fb::TagCategory category = delfos::fb::TagCategory_ModulePath,
    const char *value = nullptr,
    delfos::fb::ContentKind kind = delfos::fb::ContentKind_Function,
    delfos::fb::MemoryLayer memory_layer = delfos::fb::MemoryLayer_Episodic,
    const char *symbol_name = nullptr,
    const char *signature = nullptr,
    const char *docstring = nullptr,
    const char *body = nullptr,
    const std::vector<float> *embedding = nullptr,
    const char *embedding_model = nullptr,
    const char *embedding_model_version = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto deleted_by_commit__ = deleted_by_commit ? _fbb.CreateString(deleted_by_commit) : 0;
  auto source_file__ = source_file ? _fbb.CreateString(source_file) : 0;
  auto git_sha__ = git_sha ? _fbb.CreateString(git_sha) : 0;
  auto text__ = text ? _fbb.CreateString(text) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  auto symbol_name__ = symbol_name ? _fbb.CreateString(symbol_name) : 0;
  auto signature__ = signature ? _fbb.CreateString(signature) : 0;
  auto docstring__ = docstring ? _fbb.CreateString(docstring) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  auto embedding__ = embedding ? _fbb.CreateVector<float>(*embedding) : 0;
  auto embedding_model__ = embedding_model ? _fbb.CreateString(embedding_model) : 0;
  auto embedding_model_version__ = embedding_model_version ? _fbb.CreateString(embedding_model_version) : 0;
  return delfos::fb::CreateNode(
      _fbb,
      id__,
      type,
      status,
      indexed_at,
      deleted_at,
      deleted_by_commit__,
      source_file__,
      git_sha__,
      cue_type,
      text__,
      category,
      value__,
      kind,
      memory_layer,
      symbol_name__,
      signature__,
      docstring__,
      body__,
      embedding__,
      embedding_model__,
      embedding_model_version__);
}

::flatbuffers::Offset<Node> CreateNode(::flatbuffers::FlatBufferBuilder &_fbb, const NodeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct EdgeT : public ::flatbuffers::NativeTable {
  typedef Edge TableType;
  uint32_t source = 0;
  uint32_t target = 0;
  delfos::fb::EdgeType type = delfos::fb::EdgeType_CueOf;
  std::string source_file{};
  std::string git_sha{};
  int64_t indexed_at = 0;
};

struct Edge FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EdgeT NativeTableType;
  typedef EdgeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE = 4,
    VT_TARGET = 6,
    VT_TYPE = 8,
    VT_SOURCE_FILE = 10,
    VT_GIT_SHA = 12,
    VT_INDEXED_AT = 14
  };
  uint32_t source() const {
    return GetField<uint32_t>(VT_SOURCE, 0);
  }
  uint32_t target() const {
    return GetField<uint32_t>(VT_TARGET, 0);
  }
  delfos::fb::EdgeType type() const {
    return static_cast<delfos::fb::EdgeType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *source_file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_FILE);
  }
  const ::flatbuffers::String *git_sha() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GIT_SHA);
  }
  int64_t indexed_at() const {
    return GetField<int64_t>(VT_INDEXED_AT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TARGET, 4) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_SOURCE_FILE) &&
           verifier.VerifyString(source_file()) &&
           VerifyOffset(verifier, VT_GIT_SHA) &&
           verifier.VerifyString(git_sha()) &&
           VerifyField<int64_t>(verifier, VT_INDEXED_AT, 8) &&
           verifier.EndTable();
  }
  EdgeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EdgeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Edge> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EdgeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EdgeBuilder {
  typedef Edge Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source(uint32_t source) {
    fbb_.AddElement<uint32_t>(Edge::VT_SOURCE, source, 0);
  }
  void add_target(uint32_t target) {
    fbb_.AddElement<uint32_t>(Edge::VT_TARGET, target, 0);
  }
  void add_type(delfos::fb::EdgeType type) {
    fbb_.AddElement<int8_t>(Edge::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_source_file(::flatbuffers::Offset<::flatbuffers::String> source_file) {
    fbb_.AddOffset(Edge::VT_SOURCE_FILE, source_file);
  }
  void add_git_sha(::flatbuffers::Offset<::flatbuffers::String> git_sha) {
    fbb_.AddOffset(Edge::VT_GIT_SHA, git_sha);
  }
  void add_indexed_at(int64_t indexed_at) {
    fbb_.AddElement<int64_t>(Edge::VT_INDEXED_AT, indexed_at, 0);
  }
  explicit EdgeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Edge> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Edge>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Edge> CreateEdge(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t source = 0,
    uint32_t target = 0,
    delfos::fb::EdgeType type = delfos::fb::EdgeType_CueOf,
    ::flatbuffers::Offset<::flatbuffers::String> source_file = 0,
    ::flatbuffers::Offset<::flatbuffers::String> git_sha = 0,
    int64_t indexed_at = 0) {
  EdgeBuilder builder_(_fbb);
  builder_.add_indexed_at(indexed_at);
  builder_.add_git_sha(git_sha);
  builder_.add_source_file(source_file);
  builder_.add_target(target);
  builder_.add_source(source);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Edge> CreateEdgeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t source = 0,
    uint32_t target = 0,
    delfos::fb::EdgeType type = delfos::fb::EdgeType_CueOf,
    const char *source_file = nullptr,
    const char *git_sha = nullptr,
    int64_t indexed_at = 0) {
  auto source_file__ = source_file ? _fbb.CreateString(source_file) : 0;
  auto git_sha__ = git_sha ? _fbb.CreateString(git_sha) : 0;
  return delfos::fb::CreateEdge(
      _fbb,
      source,
      target,
      type,
      source_file__,
      git_sha__,
      indexed_at);
}

::flatbuffers::Offset<Edge> CreateEdge(::flatbuffers::FlatBufferBuilder &_fbb, const EdgeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ManifestEntryT : public ::flatbuffers::NativeTable {
  typedef ManifestEntry TableType;
  std::string file_path{};
  std::string git_sha{};
  int64_t indexed_at = 0;
};

struct ManifestEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ManifestEntryT NativeTableType;
  typedef ManifestEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_PATH = 4,
    VT_GIT_SHA = 6,
    VT_INDEXED_AT = 8
  };
  const ::flatbuffers::String *file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_PATH);
  }
  const ::flatbuffers::String *git_sha() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GIT_SHA);
  }
  int64_t indexed_at() const {
    return GetField<int64_t>(VT_INDEXED_AT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_PATH) &&
           verifier.VerifyString(file_path()) &&
           VerifyOffset(verifier, VT_GIT_SHA) &&
           verifier.VerifyString(git_sha()) &&
           VerifyField<int64_t>(verifier, VT_INDEXED_AT, 8) &&
           verifier.EndTable();
  }
  ManifestEntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ManifestEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ManifestEntry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ManifestEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ManifestEntryBuilder {
  typedef ManifestEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_path(::flatbuffers::Offset<::flatbuffers::String> file_path) {
    fbb_.AddOffset(ManifestEntry::VT_FILE_PATH, file_path);
  }
  void add_git_sha(::flatbuffers::Offset<::flatbuffers::String> git_sha) {
    fbb_.AddOffset(ManifestEntry::VT_GIT_SHA, git_sha);
  }
  void add_indexed_at(int64_t indexed_at) {
    fbb_.AddElement<int64_t>(ManifestEntry::VT_INDEXED_AT, indexed_at, 0);
  }
  explicit ManifestEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ManifestEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ManifestEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ManifestEntry> CreateManifestEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> git_sha = 0,
    int64_t indexed_at = 0) {
  ManifestEntryBuilder builder_(_fbb);
  builder_.add_indexed_at(indexed_at);
  builder_.add_git_sha(git_sha);
  builder_.add_file_path(file_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ManifestEntry> CreateManifestEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_path = nullptr,
    const char *git_sha = nullptr,
    int64_t indexed_at = 0) {
  auto file_path__ = file_path ? _fbb.CreateString(file_path) : 0;
  auto git_sha__ = git_sha ? _fbb.CreateString(git_sha) : 0;
  return delfos::fb::CreateManifestEntry(
      _fbb,
      file_path__,
      git_sha__,
      indexed_at);
}

::flatbuffers::Offset<ManifestEntry> CreateManifestEntry(::flatbuffers::FlatBufferBuilder &_fbb, const ManifestEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SnapshotT : public ::flatbuffers::NativeTable {
  typedef Snapshot TableType;
  std::vector<std::unique_ptr<delfos::fb::NodeT>> nodes{};
  std::vector<std::unique_ptr<delfos::fb::EdgeT>> edges{};
  std::vector<std::unique_ptr<delfos::fb::ManifestEntryT>> manifest{};
  SnapshotT() = default;
  SnapshotT(const SnapshotT &o);
  SnapshotT(SnapshotT&&) FLATBUFFERS_NOEXCEPT = default;
  SnapshotT &operator=(SnapshotT o) FLATBUFFERS_NOEXCEPT;
};

struct Snapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnapshotT NativeTableType;
  typedef SnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODES = 4,
    VT_EDGES = 6,
    VT_MANIFEST = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Node>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Node>> *>(VT_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Edge>> *edges() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Edge>> *>(VT_EDGES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::ManifestEntry>> *manifest() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::ManifestEntry>> *>(VT_MANIFEST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           VerifyOffset(verifier, VT_EDGES) &&
           verifier.VerifyVector(edges()) &&
           verifier.VerifyVectorOfTables(edges()) &&
           VerifyOffset(verifier, VT_MANIFEST) &&
           verifier.VerifyVector(manifest()) &&
           verifier.VerifyVectorOfTables(manifest()) &&
           verifier.EndTable();
  }
  SnapshotT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Snapshot> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SnapshotBuilder {
  typedef Snapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Node>>> nodes) {
    fbb_.AddOffset(Snapshot::VT_NODES, nodes);
  }
  void add_edges(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Edge>>> edges) {
    fbb_.AddOffset(Snapshot::VT_EDGES, edges);
  }
  void add_manifest(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::ManifestEntry>>> manifest) {
    fbb_.AddOffset(Snapshot::VT_MANIFEST, manifest);
  }
  explicit SnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Snapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Snapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Node>>> nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::Edge>>> edges = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<delfos::fb::ManifestEntry>>> manifest = 0) {
  SnapshotBuilder builder_(_fbb);
  builder_.add_manifest(manifest);
  builder_.add_edges(edges);
  builder_.add_nodes(nodes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Snapshot> CreateSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<delfos::fb::Node>> *nodes = nullptr,
    const std::vector<::flatbuffers::Offset<delfos::fb::Edge>> *edges = nullptr,
    const std::vector<::flatbuffers::Offset<delfos::fb::ManifestEntry>> *manifest = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::Node>>(*nodes) : 0;
  auto edges__ = edges ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::Edge>>(*edges) : 0;
  auto manifest__ = manifest ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::ManifestEntry>>(*manifest) : 0;
  return delfos::fb::CreateSnapshot(
      _fbb,
      nodes__,
      edges__,
      manifest__);
}

::flatbuffers::Offset<Snapshot> CreateSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline NodeT *Node::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<NodeT>(new NodeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Node::UnPackTo(NodeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = type(); _o->type = _e; }
  { auto _e = status(); _o->status = _e; }
  { auto _e = indexed_at(); _o->indexed_at = _e; }
  { auto _e = deleted_at(); _o->deleted_at = _e; }
  { auto _e = deleted_by_commit(); if (_e) _o->deleted_by_commit = _e->str(); }
  { auto _e = source_file(); if (_e) _o->source_file = _e->str(); }
  { auto _e = git_sha(); if (_e) _o->git_sha = _e->str(); }
  { auto _e = cue_type(); _o->cue_type = _e; }
  { auto _e = text(); if (_e) _o->text = _e->str(); }
  { auto _e = category(); _o->category = _e; }
  { auto _e = value(); if (_e) _o->value = _e->str(); }
  { auto _e = kind(); _o->kind = _e; }
  { auto _e = memory_layer(); _o->memory_layer = _e; }
  { auto _e = symbol_name(); if (_e) _o->symbol_name = _e->str(); }
  { auto _e = signature(); if (_e) _o->signature = _e->str(); }
  { auto _e = docstring(); if (_e) _o->docstring = _e->str(); }
  { auto _e = body(); if (_e) _o->body = _e->str(); }
  { auto _e = embedding(); if (_e) { _o->embedding.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->embedding[_i] = _e->Get(_i); } } else { _o->embedding.resize(0); } }
  { auto _e = embedding_model(); if (_e) _o->embedding_model = _e->str(); }
  { auto _e = embedding_model_version(); if (_e) _o->embedding_model_version = _e->str(); }
}

inline ::flatbuffers::Offset<Node> Node::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NodeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateNode(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Node> CreateNode(::flatbuffers::FlatBufferBuilder &_fbb, const NodeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const NodeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id.empty() ? 0 : _fbb.CreateString(_o->id);
  auto _type = _o->type;
  auto _status = _o->status;
  auto _indexed_at = _o->indexed_at;
  auto _deleted_at = _o->deleted_at;
  auto _deleted_by_commit = _o->deleted_by_commit.empty() ? 0 : _fbb.CreateString(_o->deleted_by_commit);
  auto _source_file = _o->source_file.empty() ? 0 : _fbb.CreateString(_o->source_file);
  auto _git_sha = _o->git_sha.empty() ? 0 : _fbb.CreateString(_o->git_sha);
  auto _cue_type = _o->cue_type;
  auto _text = _o->text.empty() ? 0 : _fbb.CreateString(_o->text);
  auto _category = _o->category;
  auto _value = _o->value.empty() ? 0 : _fbb.CreateString(_o->value);
  auto _kind = _o->kind;
  auto _memory_layer = _o->memory_layer;
  auto _symbol_name = _o->symbol_name.empty() ? 0 : _fbb.CreateString(_o->symbol_name);
  auto _signature = _o->signature.empty() ? 0 : _fbb.CreateString(_o->signature);
  auto _docstring = _o->docstring.empty() ? 0 : _fbb.CreateString(_o->docstring);
  auto _body = _o->body.empty() ? 0 : _fbb.CreateString(_o->body);
  auto _embedding = _o->embedding.size() ? _fbb.CreateVector(_o->embedding) : 0;
  auto _embedding_model = _o->embedding_model.empty() ? 0 : _fbb.CreateString(_o->embedding_model);
  auto _embedding_model_version = _o->embedding_model_version.empty() ? 0 : _fbb.CreateString(_o->embedding_model_version);
  return delfos::fb::CreateNode(
      _fbb,
      _id,
      _type,
      _status,
      _indexed_at,
      _deleted_at,
      _deleted_by_commit,
      _source_file,
      _git_sha,
      _cue_type,
      _text,
      _category,
      _value,
      _kind,
      _memory_layer,
      _symbol_name,
      _signature,
      _docstring,
      _body,
      _embedding,
      _embedding_model,
      _embedding_model_version);
}

inline EdgeT *Edge::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EdgeT>(new EdgeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Edge::UnPackTo(EdgeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source(); _o->source = _e; }
  { auto _e = target(); _o->target = _e; }
  { auto _e = type(); _o->type = _e; }
  { auto _e = source_file(); if (_e) _o->source_file = _e->str(); }
  { auto _e = git_sha(); if (_e) _o->git_sha = _e->str(); }
  { auto _e = indexed_at(); _o->indexed_at = _e; }
}

inline ::flatbuffers::Offset<Edge> Edge::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EdgeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEdge(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Edge> CreateEdge(::flatbuffers::FlatBufferBuilder &_fbb, const EdgeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EdgeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source = _o->source;
  auto _target = _o->target;
  auto _type = _o->type;
  auto _source_file = _o->source_file.empty() ? 0 : _fbb.CreateString(_o->source_file);
  auto _git_sha = _o->git_sha.empty() ? 0 : _fbb.CreateString(_o->git_sha);
  auto _indexed_at = _o->indexed_at;
  return delfos::fb::CreateEdge(
      _fbb,
      _source,
      _target,
      _type,
      _source_file,
      _git_sha,
      _indexed_at);
}

inline ManifestEntryT *ManifestEntry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ManifestEntryT>(new ManifestEntryT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ManifestEntry::UnPackTo(ManifestEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = file_path(); if (_e) _o->file_path = _e->str(); }
  { auto _e = git_sha(); if (_e) _o->git_sha = _e->str(); }
  { auto _e = indexed_at(); _o->indexed_at = _e; }
}

inline ::flatbuffers::Offset<ManifestEntry> ManifestEntry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ManifestEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateManifestEntry(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ManifestEntry> CreateManifestEntry(::flatbuffers::FlatBufferBuilder &_fbb, const ManifestEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ManifestEntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _file_path = _o->file_path.empty() ? 0 : _fbb.CreateString(_o->file_path);
  auto _git_sha = _o->git_sha.empty() ? 0 : _fbb.CreateString(_o->git_sha);
  auto _indexed_at = _o->indexed_at;
  return delfos::fb::CreateManifestEntry(
      _fbb,
      _file_path,
      _git_sha,
      _indexed_at);
}

inline SnapshotT::SnapshotT(const SnapshotT &o) {
  nodes.reserve(o.nodes.size());
  for (const auto &nodes_ : o.nodes) { nodes.emplace_back((nodes_) ? new delfos::fb::NodeT(*nodes_) : nullptr); }
  edges.reserve(o.edges.size());
  for (const auto &edges_ : o.edges) { edges.emplace_back((edges_) ? new delfos::fb::EdgeT(*edges_) : nullptr); }
  manifest.reserve(o.manifest.size());
  for (const auto &manifest_ : o.manifest) { manifest.emplace_back((manifest_) ? new delfos::fb::ManifestEntryT(*manifest_) : nullptr); }
}

inline SnapshotT &SnapshotT::operator=(SnapshotT o) FLATBUFFERS_NOEXCEPT {
  std::swap(nodes, o.nodes);
  std::swap(edges, o.edges);
  std::swap(manifest, o.manifest);
  return *this;
}

inline SnapshotT *Snapshot::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SnapshotT>(new SnapshotT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Snapshot::UnPackTo(SnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = nodes(); if (_e) { _o->nodes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->nodes[_i]) { _e->Get(_i)->UnPackTo(_o->nodes[_i].get(), _resolver); } else { _o->nodes[_i] = std::unique_ptr<delfos::fb::NodeT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->nodes.resize(0); } }
  { auto _e = edges(); if (_e) { _o->edges.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->edges[_i]) { _e->Get(_i)->UnPackTo(_o->edges[_i].get(), _resolver); } else { _o->edges[_i] = std::unique_ptr<delfos::fb::EdgeT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->edges.resize(0); } }
  { auto _e = manifest(); if (_e) { _o->manifest.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->manifest[_i]) { _e->Get(_i)->UnPackTo(_o->manifest[_i].get(), _resolver); } else { _o->manifest[_i] = std::unique_ptr<delfos::fb::ManifestEntryT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->manifest.resize(0); } }
}

inline ::flatbuffers::Offset<Snapshot> Snapshot::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSnapshot(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SnapshotT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _nodes = _o->nodes.size() ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::Node>> (_o->nodes.size(), [](size_t i, _VectorArgs *__va) { return CreateNode(*__va->__fbb, __va->__o->nodes[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _edges = _o->edges.size() ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::Edge>> (_o->edges.size(), [](size_t i, _VectorArgs *__va) { return CreateEdge(*__va->__fbb, __va->__o->edges[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _manifest = _o->manifest.size() ? _fbb.CreateVector<::flatbuffers::Offset<delfos::fb::ManifestEntry>> (_o->manifest.size(), [](size_t i, _VectorArgs *__va) { return CreateManifestEntry(*__va->__fbb, __va->__o->manifest[i].get(), __va->__rehasher); }, &_va ) : 0;
  return delfos::fb::CreateSnapshot(
      _fbb,
      _nodes,
      _edges,
      _manifest);
}

inline const delfos::fb::Snapshot *GetSnapshot(const void *buf) {
  return ::flatbuffers::GetRoot<delfos::fb::Snapshot>(buf);
}

inline const delfos::fb::Snapshot *GetSizePrefixedSnapshot(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<delfos::fb::Snapshot>(buf);
}

inline bool VerifySnapshotBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<delfos::fb::Snapshot>(nullptr);
}

inline bool VerifySizePrefixedSnapshotBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<delfos::fb::Snapshot>(nullptr);
}

inline void FinishSnapshotBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<delfos::fb::Snapshot> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSnapshotBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<delfos::fb::Snapshot> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<delfos::fb::SnapshotT> UnPackSnapshot(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<delfos::fb::SnapshotT>(GetSnapshot(buf)->UnPack(res));
}

inline std::unique_ptr<delfos::fb::SnapshotT> UnPackSizePrefixedSnapshot(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<delfos::fb::SnapshotT>(GetSizePrefixedSnapshot(buf)->UnPack(res));
}

}  // namespace fb
}  // namespace delfos

#endif  // FLATBUFFERS_GENERATED_DELFOS_DELFOS_FB_H_
